.TH LATCH 8 "December 29, 2014" "1.1" "System Management Commands"
.
.
.SH "NAME"
latch \- the safety switch for your digital life
.
.
.SH "SYNOPSIS"
\fBlatch\fR \-p \fIPAIRING_CODE\fR [options]
.PP
\fBlatch\fR \-s [options]
.PP
\fBlatch\fR \-o \fIOPERATION\fR [options]
.PP
\fBlatch\fR \-u [options]
.
.
.SH DESCRIPTION
.B latch
Command for pairing system with Latch.
.PP
This allows system users to pair and unpair their accounts with Latch, and 
also check their status with Latch Servers.
.PP
\fB-p\fR \fIPAIRING_CODE\fR
.RS 4          
Pair user with Latch servers.
.RE
.PP
.B -s
.RS 4
Check latch status with Latch servers.
.RE
.PP
\fB-o\fR \fIOPERATION\fR
.RS 4
Check \fBOPERATION\fR status with Latch servers.
.RE
.PP
.B -u
.RS 4
Unpair user from Latch servers.
.RE
.PP
-v
.RS 4                    
Version.
.RE
.PP
-h
.RS 4                     
Help.
.RE
.
.
.SH OPTIONS
\fB-f\fR \fICONFIG_FILE\fR
.RS 4
Get configuration parameters from \fBCONFIG_FILE\fR.
.PP
By default, if this option is not specified, configuration file is \fI/etc/latch/latch.conf\fR.
.RE
.PP
\fB-a\fR \fIACCOUNTS_FILE\fR 
.RS 4
Put and get accounts information from \fBACCOUNTS_FILE\fR.
.PP
By default, if this option is not specified, accounts file is \fI/etc/latch/latch.accounts\fR.
.RE
.
.
.SH CONFIGURATION
The latch configuration file must have the following options:
.PP
\fBapp_id\fR (required)
.RS 4
Latch application id.
.RE
.PP
\fBsecret_key\fR (required)
.RS 4
Latch secret key.
.RE
.PP
\fBlatch host\fR
.RS 4
Latch host.
.RE
.PP
\fBaction\fR
.RS 4
Specifies the action to be performed in case there is no connection to Latch servers
(that may be \fIopen\fR/\fIclose\fR).
.RE
.PP
\fBtimeout\fR (number)
.RS 4
Timeout.
.RE
.PP
.
An example configuration file:
.PP
.RS 4
app_id = SI9F...53RI
.br
secret_key = 4MjR...Q2NmRiM2Q1Y
.br
latch_host = https://latch.elevenpaths.com
.br
action = open
.br
timeout = 8
.RE

.SH EXAMPLES
\fBlatch\fR \-p Fm4Mgx
.
.
.SH FILES
/etc/latch/latch.conf
.RS 4
Default configuration file.
.RE
.PP
/etc/latch/latch.accounts
.RS 4
Default accounts file.
.RE
.
.
.SH AUTHORS
\fBlatch\fR was written by "Eleven Paths" <latch-help@support.elevenpaths.com>
.
.
.SH COPYRIGHT
Something
.
.
.SH SUPPORT
Something
.
.
.SH SEE ALSO
Something
